export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
interface StudioLayoutProps {
  children: React.ReactNode;
}

const StudioLayout: React.FC<StudioLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default StudioLayout;
